// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SchedularMessage.proto

package com.github.cronjob.protocol.entity;

public interface ExecuteResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.cronjob.ExecuteResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *执行结果
   * </pre>
   *
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <pre>
   *执行结果
   * </pre>
   *
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   *是否成功
   * </pre>
   *
   * <code>bool success = 2;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <pre>
   *错误
   * </pre>
   *
   * <code>string err = 3;</code>
   * @return The err.
   */
  String getErr();
  /**
   * <pre>
   *错误
   * </pre>
   *
   * <code>string err = 3;</code>
   * @return The bytes for err.
   */
  com.google.protobuf.ByteString
      getErrBytes();

  /**
   * <pre>
   *实际开启时间
   * </pre>
   *
   * <code>string startTime = 4;</code>
   * @return The startTime.
   */
  String getStartTime();
  /**
   * <pre>
   *实际开启时间
   * </pre>
   *
   * <code>string startTime = 4;</code>
   * @return The bytes for startTime.
   */
  com.google.protobuf.ByteString
      getStartTimeBytes();

  /**
   * <pre>
   *实际结束时间
   * </pre>
   *
   * <code>string endTime = 5;</code>
   * @return The endTime.
   */
  String getEndTime();
  /**
   * <pre>
   *实际结束时间
   * </pre>
   *
   * <code>string endTime = 5;</code>
   * @return The bytes for endTime.
   */
  com.google.protobuf.ByteString
      getEndTimeBytes();
}
