// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SchedularMessage.proto

package com.github.cronjob.protocol.entity;

public interface ExecuteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.cronjob.ExecuteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *执行器名称
   * </pre>
   *
   * <code>string handlerName = 1;</code>
   * @return The handlerName.
   */
  String getHandlerName();
  /**
   * <pre>
   *执行器名称
   * </pre>
   *
   * <code>string handlerName = 1;</code>
   * @return The bytes for handlerName.
   */
  com.google.protobuf.ByteString
      getHandlerNameBytes();

  /**
   * <pre>
   *是否串行
   * </pre>
   *
   * <code>bool serial = 2;</code>
   * @return The serial.
   */
  boolean getSerial();

  /**
   * <pre>
   *超时时间
   * </pre>
   *
   * <code>int32 executeTimeout = 3;</code>
   * @return The executeTimeout.
   */
  int getExecuteTimeout();

  /**
   * <pre>
   *执行参数
   * </pre>
   *
   * <code>string parameter = 4;</code>
   * @return The parameter.
   */
  String getParameter();
  /**
   * <pre>
   *执行参数
   * </pre>
   *
   * <code>string parameter = 4;</code>
   * @return The bytes for parameter.
   */
  com.google.protobuf.ByteString
      getParameterBytes();
}
