// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SchedularMessage.proto

package com.github.cronjob.protocol.entity;

/**
 * Protobuf type {@code com.github.cronjob.ExecuteRequest}
 */
public  final class ExecuteRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.cronjob.ExecuteRequest)
    ExecuteRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecuteRequest.newBuilder() to construct.
  private ExecuteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecuteRequest() {
    handlerName_ = "";
    parameter_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExecuteRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExecuteRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            handlerName_ = s;
            break;
          }
          case 16: {

            serial_ = input.readBool();
            break;
          }
          case 24: {

            executeTimeout_ = input.readInt32();
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            parameter_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return SchedularEntity.internal_static_com_github_cronjob_ExecuteRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return SchedularEntity.internal_static_com_github_cronjob_ExecuteRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ExecuteRequest.class, ExecuteRequest.Builder.class);
  }

  public static final int HANDLERNAME_FIELD_NUMBER = 1;
  private volatile Object handlerName_;
  /**
   * <pre>
   *执行器名称
   * </pre>
   *
   * <code>string handlerName = 1;</code>
   * @return The handlerName.
   */
  public String getHandlerName() {
    Object ref = handlerName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      handlerName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *执行器名称
   * </pre>
   *
   * <code>string handlerName = 1;</code>
   * @return The bytes for handlerName.
   */
  public com.google.protobuf.ByteString
      getHandlerNameBytes() {
    Object ref = handlerName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      handlerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERIAL_FIELD_NUMBER = 2;
  private boolean serial_;
  /**
   * <pre>
   *是否串行
   * </pre>
   *
   * <code>bool serial = 2;</code>
   * @return The serial.
   */
  public boolean getSerial() {
    return serial_;
  }

  public static final int EXECUTETIMEOUT_FIELD_NUMBER = 3;
  private int executeTimeout_;
  /**
   * <pre>
   *超时时间
   * </pre>
   *
   * <code>int32 executeTimeout = 3;</code>
   * @return The executeTimeout.
   */
  public int getExecuteTimeout() {
    return executeTimeout_;
  }

  public static final int PARAMETER_FIELD_NUMBER = 4;
  private volatile Object parameter_;
  /**
   * <pre>
   *执行参数
   * </pre>
   *
   * <code>string parameter = 4;</code>
   * @return The parameter.
   */
  public String getParameter() {
    Object ref = parameter_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      parameter_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *执行参数
   * </pre>
   *
   * <code>string parameter = 4;</code>
   * @return The bytes for parameter.
   */
  public com.google.protobuf.ByteString
      getParameterBytes() {
    Object ref = parameter_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      parameter_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getHandlerNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, handlerName_);
    }
    if (serial_ != false) {
      output.writeBool(2, serial_);
    }
    if (executeTimeout_ != 0) {
      output.writeInt32(3, executeTimeout_);
    }
    if (!getParameterBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, parameter_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getHandlerNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, handlerName_);
    }
    if (serial_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, serial_);
    }
    if (executeTimeout_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, executeTimeout_);
    }
    if (!getParameterBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, parameter_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ExecuteRequest)) {
      return super.equals(obj);
    }
    ExecuteRequest other = (ExecuteRequest) obj;

    if (!getHandlerName()
        .equals(other.getHandlerName())) return false;
    if (getSerial()
        != other.getSerial()) return false;
    if (getExecuteTimeout()
        != other.getExecuteTimeout()) return false;
    if (!getParameter()
        .equals(other.getParameter())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HANDLERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getHandlerName().hashCode();
    hash = (37 * hash) + SERIAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSerial());
    hash = (37 * hash) + EXECUTETIMEOUT_FIELD_NUMBER;
    hash = (53 * hash) + getExecuteTimeout();
    hash = (37 * hash) + PARAMETER_FIELD_NUMBER;
    hash = (53 * hash) + getParameter().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ExecuteRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExecuteRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExecuteRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExecuteRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExecuteRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExecuteRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExecuteRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExecuteRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ExecuteRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ExecuteRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ExecuteRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExecuteRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ExecuteRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.github.cronjob.ExecuteRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.cronjob.ExecuteRequest)
      ExecuteRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SchedularEntity.internal_static_com_github_cronjob_ExecuteRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SchedularEntity.internal_static_com_github_cronjob_ExecuteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ExecuteRequest.class, ExecuteRequest.Builder.class);
    }

    // Construct using com.github.cronjob.protocol.entity.ExecuteRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      handlerName_ = "";

      serial_ = false;

      executeTimeout_ = 0;

      parameter_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return SchedularEntity.internal_static_com_github_cronjob_ExecuteRequest_descriptor;
    }

    @Override
    public ExecuteRequest getDefaultInstanceForType() {
      return ExecuteRequest.getDefaultInstance();
    }

    @Override
    public ExecuteRequest build() {
      ExecuteRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ExecuteRequest buildPartial() {
      ExecuteRequest result = new ExecuteRequest(this);
      result.handlerName_ = handlerName_;
      result.serial_ = serial_;
      result.executeTimeout_ = executeTimeout_;
      result.parameter_ = parameter_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ExecuteRequest) {
        return mergeFrom((ExecuteRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ExecuteRequest other) {
      if (other == ExecuteRequest.getDefaultInstance()) return this;
      if (!other.getHandlerName().isEmpty()) {
        handlerName_ = other.handlerName_;
        onChanged();
      }
      if (other.getSerial() != false) {
        setSerial(other.getSerial());
      }
      if (other.getExecuteTimeout() != 0) {
        setExecuteTimeout(other.getExecuteTimeout());
      }
      if (!other.getParameter().isEmpty()) {
        parameter_ = other.parameter_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ExecuteRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ExecuteRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object handlerName_ = "";
    /**
     * <pre>
     *执行器名称
     * </pre>
     *
     * <code>string handlerName = 1;</code>
     * @return The handlerName.
     */
    public String getHandlerName() {
      Object ref = handlerName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        handlerName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *执行器名称
     * </pre>
     *
     * <code>string handlerName = 1;</code>
     * @return The bytes for handlerName.
     */
    public com.google.protobuf.ByteString
        getHandlerNameBytes() {
      Object ref = handlerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        handlerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *执行器名称
     * </pre>
     *
     * <code>string handlerName = 1;</code>
     * @param value The handlerName to set.
     * @return This builder for chaining.
     */
    public Builder setHandlerName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      handlerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *执行器名称
     * </pre>
     *
     * <code>string handlerName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHandlerName() {

      handlerName_ = getDefaultInstance().getHandlerName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *执行器名称
     * </pre>
     *
     * <code>string handlerName = 1;</code>
     * @param value The bytes for handlerName to set.
     * @return This builder for chaining.
     */
    public Builder setHandlerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      handlerName_ = value;
      onChanged();
      return this;
    }

    private boolean serial_ ;
    /**
     * <pre>
     *是否串行
     * </pre>
     *
     * <code>bool serial = 2;</code>
     * @return The serial.
     */
    public boolean getSerial() {
      return serial_;
    }
    /**
     * <pre>
     *是否串行
     * </pre>
     *
     * <code>bool serial = 2;</code>
     * @param value The serial to set.
     * @return This builder for chaining.
     */
    public Builder setSerial(boolean value) {

      serial_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *是否串行
     * </pre>
     *
     * <code>bool serial = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSerial() {

      serial_ = false;
      onChanged();
      return this;
    }

    private int executeTimeout_ ;
    /**
     * <pre>
     *超时时间
     * </pre>
     *
     * <code>int32 executeTimeout = 3;</code>
     * @return The executeTimeout.
     */
    public int getExecuteTimeout() {
      return executeTimeout_;
    }
    /**
     * <pre>
     *超时时间
     * </pre>
     *
     * <code>int32 executeTimeout = 3;</code>
     * @param value The executeTimeout to set.
     * @return This builder for chaining.
     */
    public Builder setExecuteTimeout(int value) {

      executeTimeout_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *超时时间
     * </pre>
     *
     * <code>int32 executeTimeout = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearExecuteTimeout() {

      executeTimeout_ = 0;
      onChanged();
      return this;
    }

    private Object parameter_ = "";
    /**
     * <pre>
     *执行参数
     * </pre>
     *
     * <code>string parameter = 4;</code>
     * @return The parameter.
     */
    public String getParameter() {
      Object ref = parameter_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        parameter_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *执行参数
     * </pre>
     *
     * <code>string parameter = 4;</code>
     * @return The bytes for parameter.
     */
    public com.google.protobuf.ByteString
        getParameterBytes() {
      Object ref = parameter_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        parameter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *执行参数
     * </pre>
     *
     * <code>string parameter = 4;</code>
     * @param value The parameter to set.
     * @return This builder for chaining.
     */
    public Builder setParameter(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      parameter_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *执行参数
     * </pre>
     *
     * <code>string parameter = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearParameter() {

      parameter_ = getDefaultInstance().getParameter();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *执行参数
     * </pre>
     *
     * <code>string parameter = 4;</code>
     * @param value The bytes for parameter to set.
     * @return This builder for chaining.
     */
    public Builder setParameterBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      parameter_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.cronjob.ExecuteRequest)
  }

  // @@protoc_insertion_point(class_scope:com.github.cronjob.ExecuteRequest)
  private static final ExecuteRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ExecuteRequest();
  }

  public static ExecuteRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecuteRequest>
      PARSER = new com.google.protobuf.AbstractParser<ExecuteRequest>() {
    @Override
    public ExecuteRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExecuteRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExecuteRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ExecuteRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public ExecuteRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

