// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SchedularMessage.proto

package com.github.cronjob.protocol.entity;

public final class SchedularEntity {
  private SchedularEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_cronjob_ExecuteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_cronjob_ExecuteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_cronjob_ExecuteResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_cronjob_ExecuteResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026SchedularMessage.proto\022\022com.github.cro" +
      "njob\"`\n\016ExecuteRequest\022\023\n\013handlerName\030\001 " +
      "\001(\t\022\016\n\006serial\030\002 \001(\010\022\026\n\016executeTimeout\030\003 " +
      "\001(\005\022\021\n\tparameter\030\004 \001(\t\"b\n\rExecuteResult\022" +
      "\017\n\007message\030\001 \001(\t\022\017\n\007success\030\002 \001(\010\022\013\n\003err" +
      "\030\003 \001(\t\022\021\n\tstartTime\030\004 \001(\t\022\017\n\007endTime\030\005 \001" +
      "(\tB7\n\"com.github.cronjob.protocol.entity" +
      "B\017SchedularEntityP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_github_cronjob_ExecuteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_cronjob_ExecuteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_cronjob_ExecuteRequest_descriptor,
        new String[] { "HandlerName", "Serial", "ExecuteTimeout", "Parameter", });
    internal_static_com_github_cronjob_ExecuteResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_cronjob_ExecuteResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_cronjob_ExecuteResult_descriptor,
        new String[] { "Message", "Success", "Err", "StartTime", "EndTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
